#!/usr/bin/env bash
# Rebuild the whole report from the live database: snapshot -> analysis -> page (Phase 5).
# Safe to re-run at any time; every step is deterministic and refuses to write when a check fails.
#
#   scripts/refresh.sh              refresh the working tree, leave committing to me
#   scripts/refresh.sh --commit     also commit the regenerated files when they changed
#   scripts/refresh.sh --check      verify the pipeline without touching the working tree
#
# Publishing is deliberately NOT part of this. The page is republished by hand, so a scheduled run can never push
# something outward without someone looking at it first.
set -euo pipefail

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$REPO"

COMMIT=0
CHECK=0
for argument in "$@"; do
  case "$argument" in
    --commit) COMMIT=1 ;;
    --check) CHECK=1 ;;
    -h | --help) sed -n '2,12p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) printf 'refresh: unknown option %s (see --help)\n' "$argument" >&2; exit 2 ;;
  esac
done

step() { printf '\n== %s\n' "$1"; }

if ((CHECK)); then
  WORKDIR=$(mktemp -d)
  trap 'rm -rf "$WORKDIR"' EXIT
  step "checking the pipeline without writing to the working tree"
  ./scripts/check-redactions.py --self-test
  ./scripts/snapshot.py --check-determinism --out "$WORKDIR/snapshot.json"
  ./scripts/analyse.py --snapshot "$WORKDIR/snapshot.json" --out "$WORKDIR/analysis.json"
  ./scripts/build-site.py --snapshot "$WORKDIR/snapshot.json" --analysis "$WORKDIR/analysis.json" \
    --out "$WORKDIR/index.html"
  ./scripts/check-redactions.py "$WORKDIR/snapshot.json" "$WORKDIR/analysis.json" "$WORKDIR/index.html"
  printf '\nrefresh: the pipeline is healthy; nothing was written\n'
  exit 0
fi

step "1/4  redaction guard"
./scripts/check-redactions.py --self-test

step "2/4  snapshot"
./scripts/snapshot.py

step "3/4  analysis"
# analyse.py exits non-zero when its figures do not reconcile against the snapshot, and set -e stops us here.
./scripts/analyse.py

step "4/4  page"
./scripts/build-site.py

step "verifying what was written"
./scripts/check-redactions.py data/snapshot-*.json data/analysis-*.json site/index.html

if ((COMMIT)); then
  if [[ -z "$(git status --porcelain data site)" ]]; then
    printf '\nrefresh: no change to commit — the window produced identical output\n'
    exit 0
  fi
  WINDOW=$(python3 -c 'import json,glob,sys; f=sorted(glob.glob("data/snapshot-*.json"))[-1];
print(json.load(open(f))["meta"]["window_end"][:16])')
  git add data site
  # The pre-commit hook runs the redaction check again: a generated file can still be edited by hand before a commit.
  git commit -q -m "Refresh the honeypot report through ${WINDOW} UTC

Regenerated by scripts/refresh.sh. Data only; the published page is
updated by hand so nothing goes outward unreviewed."
  printf '\nrefresh: committed %s\n' "$(git log --oneline -1)"
else
  printf '\nrefresh: working tree updated. Review, then commit, then republish the page by hand.\n'
  git status --short data site || true
fi
